Update optaplanner version during release (#1125)
* Initial test version update

* # This is a combination of 11 commits.
# This is the 1st commit message:

Remove quite mode on grep check
Enclose to ""
Stage build.gradle as well

# This is the commit message #2:

Add build phase to test updated versions

# The commit message #3 will be skipped:

# Cleanup testing code

# The commit message #4 will be skipped:

# Add removed stages

# This is the commit message #5:

Update Jenkinsfile.deploy

Co-authored-by: Radovan Synek <rsynek@redhat.com>
# This is the commit message #6:

Remove removeJbossNexusFromMavenAndGradle
Since we need to remove Nexus only in stable will use it only for stable branch after hard reset in a separate commit

# The commit message #7 will be skipped:

# Stage pom and gradle files in one commit
#
# Co-authored-by: Radovan Synek <rsynek@redhat.com>

# The commit message #8 will be skipped:

# Create PR for release branch
#
# Create PR with changed versions in pom.xml and build.gradle
#
# Clean up removeJbossNexusFromMavenAndGradle

# The commit message #9 will be skipped:

# Remove unnecessary commit
#
# Careful with commitments in a range. If files have not been changed and you add it and commit then git will return exit code 1 no files matched

# The commit message #10 will be skipped:

# Test Create PRs without VRP blocker

# The commit message #11 will be skipped:

# Add build branch property for quickstarts
#
# In case if it is release - base branch will be gathered from build branch. It is getting generated automatically from kogito pipelines.
#
# Cases for different base usages:
# {release, nightly, custom}
# And they related branches that would be used
# {release branch, development, params.QUICKSTARTS_BUILD_BRANCH_NAME}

* Remove quite mode on grep check
Enclose to ""
Stage build.gradle as well

Add build phase to test updated versions

Update Jenkinsfile.deploy

Co-authored-by: Radovan Synek <rsynek@redhat.com>

Remove removeJbossNexusFromMavenAndGradle
Since we need to remove Nexus only in stable will use it only for stable branch after hard reset in a separate commit

Update and reset stable branch

Despite other repo quickstarts need to be reset to stable from release branch

Additionally it should not contain JBoss nexus

So I create a branch from release and change pom and gradle files to not contain nexus repo, then I use forcePush function from https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/131

Add promotion of the protection properties

Return false if dismiss_stale_reviews or require_code_owner_reviews is null

* Assert protection does not changed for other then force push properties

Added check that other then allow force push protection properties stays the same after protection update
Reorganized code to fit in one screen
Removed allowEmptyResults flag from sh calls

* Apply suggestions from code review

Spacing and stage rename

Co-authored-by: Radovan Synek <rsynek@redhat.com>

* Add assertGithubCLI function

Checks if gh utility to send authorized requests is available in ghPath

* Add fail fast messages

If put request will fail to update allow force push then it will fail on assert after the command will be executed
In case if there was some unexpected difference in protection then the message would be:
```
ERROR: Protection settings lost
Before:
{
  "url": "https://api.github.com/repos/dupliaka/optaplanner-quickstarts/branches/stable/protection",
  "required_pull_request_reviews": {
    "url": "https://api.github.com/repos/dupliaka/optaplanner-quickstarts/branches/stable/protection/required_pull_request_reviews",
    "dismiss_stale_reviews": false,
    "require_code_owner_reviews": false
  },
  "enforce_admins": {
    "url": "https://api.github.com/repos/dupliaka/optaplanner-quickstarts/branches/stable/protection/enforce_admins",
    "enabled": false
  },
  "required_linear_history": {
    "enabled": false
  },
  "allow_deletions": {
    "enabled": false
  }
}

After:
{
  "url": "https://api.github.com/repos/dupliaka/optaplanner-quickstarts/branches/stable/protection",
  "required_pull_request_reviews": {
    "url": "https://api.github.com/repos/dupliaka/optaplanner-quickstarts/branches/stable/protection/required_pull_request_reviews",
    "dismiss_stale_reviews": false,
    "require_code_owner_reviews": false
  },
  "enforce_admins": {
    "url": "https://api.github.com/repos/dupliaka/optaplanner-quickstarts/branches/stable/protection/enforce_admins",
    "enabled": false
  },
  "required_linear_history": {
    "enabled": false
  },
  "allow_force_pushes": {
    "enabled": true
  },
  "allow_deletions": {
    "enabled": false
  }
}

Differences:
14a15,17
>   "allow_force_pushes": {
>     "enabled": true
>   },

Protection parameters:
{
  "required_status_checks": null,
  "required_pull_request_reviews": {
    "dismiss_stale_reviews": false,
    "require_code_owner_reviews": false
  },
  "enforce_admins": false,
  "restrictions": null,
  "allow_force_pushes": true
}
 Please rollback to Before state and update getProtectionMapScript
 ```

Co-authored-by: adupliak <adupliaka@gmail.com>
Co-authored-by: Radovan Synek <rsynek@redhat.com>